### ISSUE TITLE
Usage of users

### ISSUE THREAD

**Issue by mortag** [alireza0/s-ui#146]
Dear Developer Team,

Thank you for releasing your app. I have a question and I would appreciate if you could help me.

Due to a lack of resources, I don't want to install the full app. Instead, I only want to install sing-box from the source code. I'm specifically interested in using the Hysteria2 protocol. However, I'm not sure how to monitor the traffic of each individual user.

Is it possible for you to provide any hints or guidance about this? For example, is there an option to enable debug logging or any other features that could help me track the traffic usage per user?

I'd be grateful for any assistance you can provide. Please let me know if you need any clarification or have additional questions.

Best regards,

**Comment by alireza0** [comment]
Dear @mortag ,

First you should run your sing-box core with v2ray_api enabled with listenning port.
Then you can get traffic usage information by GRPC call to this port.
You can follow traffic job and `v2rayApi.go` in backend\singbox.

Good luck

**Comment by mortag** [comment]
Daer Alireza,



I greatly appreciate your assistance.

Could you please explain how to use Sing-Box with the v2ray_api? I have installed the Sing-Box service and created the client configuration, but I need guidance on how to proceed.

Thank you for your help.

**Comment by alireza0** [comment]
To build sing-box with v2rayApi module, you need to mention the tag on build process:
```bash
go build -tags with_v2ray_api -o sing-box ./cmd/sing-box
```

In order to enable it in configuration, you should configure your config.json like this:
```json
{
  "inbounds": [ ...inbounds ],
  "outbounds": [ ...outbounds ],
  "route": {
    "rules": [ ...rules ]
  },
...Other Parts
  "experimental": {
    "v2ray_api": {
      "listen": "127.0.0.1:1080",
      "stats": {
        "enabled": true,
        "inbounds": [ <INBOUND TAGS> ],
        "outbounds": [ <OUTBOUND TAGS> ],
        "users": [ <USER NAMES> ]
      }
    }
  }
}
```
In this configuration, your `v2ray_api` will listen to `127.0.0.1:1080` and send you statistics of mentioned `inbounds`,`outbounds`,`users` which you enter the `TAG`/`Name` in `stats` object. [Reference](https://sing-box.sagernet.org/configuration/experimental/v2ray-api/)

GRPC call to this port, uses this proto: [code](https://github.com/SagerNet/sing-box/blob/dev-next/experimental/v2rayapi/stats.proto)

Results is a key-value which key will be like this ( [reference](https://www.v2ray.com/en/configuration/stats.html) ):
user>>>[email]>>>traffic>>>uplink

**Comment by alireza0** [comment]
It is not as easy as curl. As I mentioned, you should use GRPC to call this api.

**Comment by mortag** [comment]
Dear Alireza,
As I am not a programmer, it is challenging for me to create a new API to calculate data usage. Therefore, I have decided to use your Prefect project.

I would like to use it as a VPN specifically for gaming. To achieve this, I need it to filter all websites, except for the game sites.

Is this possible? If so, could you please guide me on how to implement it?

Thank you.

**Comment by alireza0** [comment]
I don't know which IP/Domain list you want to use.
But it is possible to define routing rules to avoid/accept traffic to a list of IPs or Domains.

**Comment by mortag** [comment]
I am wanting gratitude for the assistance you provided me. Your support was invaluable, and I genuinely appreciate the time and effort you dedicated to helping me and I am truly grateful for your kindness and generosity.

Thank you once again for your support. 
Warmest regards,
