### ISSUE TITLE
Error occurs after updating s-ui from v0.0.4 to v0.0.5

### ISSUE THREAD

**Issue by leic4u** [alireza0/s-ui#153]
**Describe the bug**

Error occurs after updating s-ui from v0.0.4 to v0.0.5

**To Reproduce**

1. use watchtower to update s-ui.
2. login to s-ui panel
3. See error

**Expected behavior**

Panel works correctly. 

**Screenshots**

![Clip_2024-06-10_16-02-09](https://github.com/alireza0/s-ui/assets/32786903/4d859b79-1a64-4192-b6fc-cd38a84da2c1)

**Comment by alireza0** [comment]
You did not run the migration process, because of using another method of upgrading.
It is important to run migrate command before running new version.
Reocmmanded upgrade solution is one of these options:
1. Using installation link.
2. Using `s-ui update` command or choosing update from `s-ui` cli script's menu

To fix your problem, install previous version again and upgrade it with one of these solutions.

Manuall solution coule be also done:
1. Downgrade to 0.0.4
2. Run pannel once.
3. Stop panel
4. Replace new `sui` file
5. Run migration maually by `/usr/local/s-ui/sui migrate`
6. Run `s-ui` service again

If you are using docker-compose solution, just put migration command in Entrypoint:
```yaml
entrypoint: "./sui migrate && ./sui"
```

**Comment by leic4u** [comment]
I added `entrypoint: "./sui migrate && ./sui"` to my docker-compose.yml and ran `docker compose up -d` to start it.

I checked `docker logs s-ui` and found the `migrate is done`. So I run the `docker compose down` to delete the containers.

And I changed the Entrypoint back to `entrypoint: "./sui"`, and ran `docker compose up -d` to start the containers.

There are also occurs error.

Should I delete the file folder `db`?

**Comment by leic4u** [comment]
Thanks bro. The message comes a little late.

I have deleted the `db` folder and prepare to config the panel again.😂😂

**Comment by leic4u** [comment]
A little suggestion: Maybe the migration should be auto-run when there is a update.

**Comment by alireza0** [comment]
Yes, it is autorun in script. But you are using docker and updating docker-compose is not in docker update process.
I will add it to docker-compose.yml
