### ISSUE TITLE
Running “s-ui” with zsh results in an error.

### ISSUE THREAD

**Issue by lingbaoboy** [alireza0/s-ui#187]
When connecting via SSH and using oh-my-zsh instead of bash, running s-ui results in an error 
` /usr/bin/s-ui: 10: Syntax error: "(" unexpected`
while it works fine when using bash.

**Comment by alireza0** [comment]
Because it is a `bash` script!
Same error may happen when you are using `sh` instead.
It is strongly recommended to run this script in a pure minimal server without any other packages.

If you are a doftware developer and like to run zsh in your shell, then you may know how to change it! :D
Add this to your .zshrc file:
```bash
alias s-ui="bash -c 's-ui'"
```
