### ISSUE TITLE
Ensure s-ui and sing-box Services Always Restart on Failure

### ISSUE THREAD

**Issue by Maneeha1234SL** [alireza0/s-ui#193]
The service unit files for s-ui and sing-box currently have Restart=on-failure. It's recommended to change this to Restart=always to ensure the services restart automatically under all circumstances, including crashes.

s-ui Service

[Unit]
Description=s-ui Service
After=network.target
Wants=network.target

[Service]
Type=simple
WorkingDirectory=/usr/local/s-ui/
ExecStart=/usr/local/s-ui/sui
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target

sing-box Service

[Unit]
Description=sing-box service
Documentation=https://sing-box.sagernet.org/
After=network.target nss-lookup.target network-online.target

[Service]
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SYS_PTRACE CAP_DAC_READ_SEARCH
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SYS_PTRACE CAP_DAC_READ_SEARCH
WorkingDirectory=/usr/local/s-ui/bin/
ExecStart=/usr/local/s-ui/bin/runSingbox.sh
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=10s
LimitNOFILE=infinity

[Install]
WantedBy=multi-user.target

**Comment by alireza0** [comment]
Using `always` is not a good choice because it restart the service even we want to stop it.
`on-failure` will restart the service on ANY unwanted exit such as craches.
Pay attention to the definitions [here](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Restart=)

![image](https://github.com/alireza0/s-ui/assets/12573084/e383004a-e5c1-4899-a0a1-02f09296d859)
