### ISSUE TITLE
sing-box state : not running 

### ISSUE THREAD

**Issue by emad465** [alireza0/s-ui#274]
درود بر شما ، علیرضا جان یه وقتا تو پنل ارور cpu میاد با اینکه سرور کانفیگش قویه و دو هسته ای و رمشم 4 عه ولی بازم ارور cpu میده نمیدونم مشکل چیه و میرم تو سرور میبینم که sing-box state : not running  عه و باید sing-box رو با گزینه 20 ری استارت کنم تا درست بشه ، چون برق اینا هم میره خدارو شکر دسترسی ندارم همش ری استارت کنم ، قبلا خیلی کم اتفاق می افتاد الان هر روز 4 بار یا بیشتر این اتفاق براش می افته اگه درستش کنی دستت درد نکنه ممنونت میشم خیلی کارت درسته رفیق

**Comment by zoroky** [comment]
دقیقا  منم همین مشکل رو  دارم سروم  2 هسته  رم 4 اینتل هست شما هم  اینتل گرفتین ؟

**Comment by zoroky** [comment]
علیرضا جان  لاگ  ها رو  هم  برات میفرستم  ممنون میشم یه راهنمایی کنی که مشکل از کجاست  و  راه حل چیه 
![image_2024-08-16_04-06-39](https://github.com/user-attachments/assets/3b022a0e-ea61-40d8-9d99-550f4f985141)
![photo_2024-08-16_04-10-16](https://github.com/user-attachments/assets/ce4a8425-5627-4300-a93e-e010ede3737d)
![photo_2024-08-16_04-10-33](https://github.com/user-attachments/assets/dd925c76-aafb-4ec5-be40-2f49752fab90)

**Comment by DeadSecure** [comment]
@zoroky 
مشکل شما اینه:
Aug 14 23:07:23 my server runSingbox.sh[18006]: FATAL[0000] create service: outbound not found for rule[2]: t.me/OutlineVpnOfficial | (2305) US
اون rule که ساختین رو حذف کنین چون outbound نداره به مشکل میخوره

**Comment by zoroky** [comment]
> @zoroky مشکل شما اینه: Aug 14 23:07:23 my server runSingbox.sh[18006]: FATAL[0000] create service: outbound not found for rule[2]: t.me/OutlineVpnOfficial | (2305) US اون rule که ساختین رو حذف کنین چون outbound نداره به مشکل میخوره

ممنون از راهنماییتون  اون مشکل رو همون موقع متوجه شدم و حلش  کردم و اصلا  تا اون rule  رو   حذف نکردم هسته حتی ریستارت هم نمیشد.
مشکل من  مربوط به  لاگ های  آخره  مثلا تاریخ  های Aug 15 23:01:10   یا  Aug 15 16:22:46  که متوجه  نیشم  چرا  اتفاق میوفته  و  هسته  رو  غیرفعال میکنه  و چند بار  در روز  هم اتفاق  میوفته  و  تا هسته  رو دستی از طریق ssh   (عدد 20 )  ریستارت  نکنم  هسته  ران نمیشه 
@DeadSecure 
@alireza0

**Comment by Hawyan999** [comment]
sing-box state:Not Running
Please enter your selection [0-27]: 22
Aug 26 02:20:24 ideal-cats-1.localdomain systemd[1]: Started sing-box.service - sing-box service.
Aug 26 02:20:24 ideal-cats-1.localdomain runSingbox.sh[165317]: INFO[0000] router: updated default interface eth0, index 2
Aug 26 02:20:24 ideal-cats-1.localdomain runSingbox.sh[165317]: INFO[0000] v2ray-api: grpc server started at 127.0.0.1:1080
Aug 26 02:20:24 ideal-cats-1.localdomain runSingbox.sh[165317]: INFO[0000] sing-box started (0.00s)
Aug 26 02:34:49 ideal-cats-1.localdomain runSingbox.sh[165311]: Signal received: restart
Aug 26 02:34:49 ideal-cats-1.localdomain runSingbox.sh[165311]: Terminating singbox PID=165317
Aug 26 02:34:50 ideal-cats-1.localdomain runSingbox.sh[173580]: FATAL[0000] create service: parse inbound[2]: missing obfs password
Aug 26 02:34:55 ideal-cats-1.localdomain runSingbox.sh[165311]: Sing-Box with PID 173580 crashed. Breaking the loop...
Aug 26 02:34:55 ideal-cats-1.localdomain systemd[1]: sing-box.service: Deactivated successfully.
Aug 26 02:48:36 ideal-cats-1.localdomain systemd[1]: Started sing-box.service - sing-box service.
Aug 26 02:48:36 ideal-cats-1.localdomain runSingbox.sh[180856]: FATAL[0000] create service: parse inbound[2]: missing obfs password
Aug 26 02:48:41 ideal-cats-1.localdomain runSingbox.sh[180855]: Sing-Box with PID 180856 crashed. Breaking the loop...
Aug 26 02:48:41 ideal-cats-1.localdomain systemd[1]: sing-box.service: Deactivated successfully

**Comment by Omidkha1** [comment]
سلام منم همچین مشکلی داشتم از اوبونتو 22.04 استفاده کردم فعلا که اوکی شده

**Comment by lonelylose** [comment]
It seems the problem is mux stream?

Aug 30 19:10:52  runSingbox.sh[12775]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 30 19:10:52  runSingbox.sh[12775]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xe6de1a]
Aug 30 19:10:52  runSingbox.sh[12775]: goroutine 11104 [running]:
Aug 30 19:10:52  runSingbox.sh[12775]: github.com/sagernet/sing-mux.(*wrapStream).Read(0x0?, {0xc0009c326e?, 0xc00052ba40?, 0x459469?})
Aug 30 19:10:52  runSingbox.sh[12775]:         github.com/sagernet/sing-mux@v0.2.0/error.go:15 +0x1a
Aug 30 19:10:52  runSingbox.sh[12775]: io.ReadAtLeast({0x716a990e0a98, 0xc0004b5780}, {0xc0009c326e, 0x2, 0x2}, 0x2)
Aug 30 19:10:52  runSingbox.sh[12775]:         io/io.go:335 +0x90
Aug 30 19:10:52  runSingbox.sh[12775]: io.ReadFull(...)
Aug 30 19:10:52  runSingbox.sh[12775]:         io/io.go:354
Aug 30 19:10:52  runSingbox.sh[12775]: encoding/binary.Read({0x716a990e0a98, 0xc0004b5780}, {0x18749f0, 0x23bbf00}, {0x13487e0, 0xc00052bbee})
Aug 30 19:10:52  runSingbox.sh[12775]:         encoding/binary/binary.go:241 +0xb4
Aug 30 19:10:52  runSingbox.sh[12775]: github.com/sagernet/sing-mux.ReadStreamRequest({0x716a990e0a98, 0xc0004b5780})
Aug 30 19:10:52  runSingbox.sh[12775]:         github.com/sagernet/sing-mux@v0.2.0/protocol.go:119 +0x50
Aug 30 19:10:52  runSingbox.sh[12775]: github.com/sagernet/sing-mux.(*Service).newConnection(0xc0000959f0, {0x186d4b8, 0xc0003ea1b0}, {0x1876e88, 0xc000698210}, {0x0, 0x0}, {{0x0, 0x0}, {{{0x0, ...}, ...}, ...}, ...})
Aug 30 19:10:52  runSingbox.sh[12775]:         github.com/sagernet/sing-mux@v0.2.0/server.go:89 +0x117
Aug 30 19:10:52  runSingbox.sh[12775]: github.com/sagernet/sing-mux.(*Service).NewConnection.func1.1()
Aug 30 19:10:52  runSingbox.sh[12775]:         github.com/sagernet/sing-mux@v0.2.0/server.go:74 +0x7e
Aug 30 19:10:52  runSingbox.sh[12775]: created by github.com/sagernet/sing-mux.(*Service).NewConnection.func1 in goroutine 11103
Aug 30 19:10:52  runSingbox.sh[12775]:         github.com/sagernet/sing-mux@v0.2.0/server.go:73 +0xde
Aug 30 19:10:53  runSingbox.sh[421]: Sing-Box with PID 12775 crashed. Breaking the loop...
Aug 30 19:10:53  systemd[1]: sing-box.service: Deactivated successfully.
Aug 30 19:10:53  systemd[1]: sing-box.service: Consumed 4min 27.014s CPU time.

**Comment by lonelylose** [comment]
https://github.com/SagerNet/sing-box/issues/2020 it may be fixed in 1.9.4 or 1.10.x, I am not sure

**Comment by zoroky** [comment]
> سلام منم همچین مشکلی داشتم از اوبونتو 22.04 استفاده کردم فعلا که اوکی شده
من  روی اوبونتو 22.04 بودم   ومشکل همچنان وجود  داشت  مشکل رو متوجه نشدم  ولی از تنظیمات هسته restart after crash   رو  روی  always  گذاشتم  تا  خودش هر موقع  هسته  not running  شد  ریستارت  بشه

**Comment by alireza0** [comment]
درود بر شما
مشکل ریستارت در نسخه بعد حل میشه
