### ISSUE TITLE
ipv6 bug and Remark bug

### ISSUE THREAD

**Issue by amaliasal** [alireza0/s-ui#319]
**Describe the bug**
When I set the Client Side’s Multi Domain in Inbounds and use IPv6 for the Address, the node links are not recognized because they lack the brackets [], and the Subscription is not recognized either.

When I set the Client Side’s Multi Domain in Inbounds and set the Remark, the node names for links and Subscription should directly use the Remark value, instead of "Inbound Tag & Remark". 

**To Reproduce**
1. Go to Inbounds,Create a VLESS
2. Click Multi Domain
3. use IPv6 for the Address
4.  links  and Subscription is not recognized

**Desktop (please complete the following information):**
 - OS: [ubuntu2204]
 - Version [1.0.0]

I would appreciate it if it could be fixed. Thank you.

**Comment by alireza0** [comment]
It is true! In multi domain you should define a domain. You can use IP, but you should be aware that ipv6 instead of domain should have []. Just please use brakets over your IPv6.
Everything in Multi-domain confguration, will change the inbound data in new link. If you want, you can add inbound tag + your text in the remark text-box

**Comment by alireza0** [comment]
In this stage, I will continue by default. After high priority tasks, I will go with optional configuration.
