### ISSUE TITLE
1.10版本中，无法生成链接

### ISSUE THREAD

**Issue by heibailiangxiangwang20** [alireza0/s-ui#334]
1.10版本中，在用户管理-二维码链接无法生成

**Comment by alireza0** [comment]
Please provide more information.
I found an issue with adding client to new empty Inbound only.

This problem is now fixed. Please re-install new version and:
1. Edit and save new inbounds ( or re-create them )
2. Edit clients which you want to add to this inbound.

Please close the issue if it is fixed in your side
